### ISSUE TITLE
Bug: Abbreviation of last name is appearing twice

### ISSUE THREAD

**Issue by somewhatabstract** [SeanMcP/aital-extension#14]
This is in the 0.5 Chrome store extension.

<img width="118" alt="image" src="https://github.com/SeanMcP/aital-extension/assets/1266297/101cd29c-8493-4944-b952-6909fac81b8a">

**Comment by SeanMcP** [comment]
@somewhatabstract The fix has landed and was submitted to the Webstore. Thanks for reporting it!
